- name: Set up Ansibne Tower Surveys with hostnames
  hosts: all
  gather_facts: False
  tasks:
  - name: Get inventory from Ansible Tower
    uri:
      url: "{{ ans_tower_url }}"
      user: "{{ ans_tower_user }}"
      password: "{{ ans_tower_password }}"
      method: GET
      force: yes
      validate_certs: no
    register: wli_12_inventory

  - debug:
      msg: "{{ wli_12_inventory }}"
