- name: Set up Ansibne Tower Surveys with hostnames
  hosts: all
  gather_facts: False
  tasks:
  - name: Get API Token
    uri:
      url: "{{ ansible_tower_url }}/api/v2/tokens/"
      method: POST
      user: "{{ ansible_tower_username }}"
      password: "{{ ansible_tower_password }}"
      validate_certs: no
      force_basic_auth: yes
      status_code: 201
      return_content: yes
    register: authtoken

  - name: Get inventory from Ansible Tower
    uri:
      url: "{{ ansible_tower_url }}/api/v2/inventories/{{ inventory_id }}/hosts/"
      headers:
        Authorization: "Bearer {{ authtoken.json.token }}"
        Content-Type: "application/json"
      validate_certs: no
      follow_redirects: all
      return_content: True
      method: GET
    register: wli_12_inventory

  - debug:
      msg: "{{ wli_12_inventory | json_query('results.name[*]') }}"
