- hosts: all
  gather_facts: false
  tasks:

    - name: Print AWS Keys
      debug:
        msg: |
          AWS Access Key is {{ AWS_ACCESS_KEY_ID }}
          AWS Secret Key is {{ AWS_SECRET_ACCESS_KEY }}
          AWS SYS Token is {{ AWS_SECURITY_TOKEN }}
