- hosts: all
  gather_facts: false
  tasks:

    - name: Print AWS Keys
      debug:
        msg: |
          AWS Access Key is {{ lookup('env','AWS_ACCESS_KEY_ID') }}
          AWS Secret Key is {{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
          AWS SYS Token is {{ lookup('env','AWS_SECURITY_TOKEN') }}
